Fix BeanDefinitionStore compile error by upgrading to Spring 4.0.3.RELEASE
FIXME: Unit test runtime errors

    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    java.lang.instrument.IllegalClassFormatException: Error while instrumenting class org/apache/maven/surefire/booter/stream/CommandDecoder.
        at org.jacoco.agent.rt_1r70et.CoverageTransformer.transform(CoverageTransformer.java:94)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
        ...
    [INFO] Running FizzBuzzTest
    java.lang.instrument.IllegalClassFormatException: Error while instrumenting class java/sql/SQLException.
        at org.jacoco.agent.rt_1r70et.CoverageTransformer.transform(CoverageTransformer.java:94)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
        ...